additional solo event and datetime field
bluecherrydvr/bluecherry-apps pull request #392
Opened 2020-09-10 13:12 UTC by tugrul

I added a trigger for solo event and additional fields datetime and dvr_name

2020-09-11 13:29 UTC, antonsviridenko commented
What does "solo" mean in this context, Bluecherry hardware capture card based on solo6x10 chips or something other?

It would be nice to have more human-readable strings instead of `array('motion_event', 'device_state', 'solo');` displayed to user.

And I missed that part in previous pull request, all strings displayed in web UI should be defined in https://github.com/bluecherrydvr/bluecherry-apps/blob/master/www/lib/lang.php instead of hardcoded literals in the code. We might need translations to other languages than English. 

https://github.com/bluecherrydvr/bluecherry-apps/blob/master/www/template/main_admin.php#L162

2020-09-11 13:31 UTC, antonsviridenko requested changes

2020-09-11 13:31 UTC, antonsviridenko commented on www/ajax/webhook.php
> +        $this->view->events = array('motion_event', 'device_state', 'solo');
see previous comment about literal strings displayed to user

2020-09-11 15:36 UTC, tugrul commented
I don't know what is it. I just implemented event types what I see in mailer.php

2020-09-16 23:30 UTC, antonsviridenko commented
Something like "Motion Event", "Device State", "Bluecherry SOLO card state"

2020-09-17 03:03 UTC, curtishall commented
Labels:

- Motion Event
- Device Status
- Bluecherry analog capture card (solo)

2020-09-17 13:17 UTC, antonsviridenko approved these changes

2020-09-17 13:17 UTC, merged