Mail Notification Settings UI & Mail Sender Library Upgrade
bluecherrydvr/bluecherry-apps pull request #398
Opened 2020-12-25 23:18 UTC by curtishall

- Enhanced mail notification settings UI
- Obsolete pear mail library dependency replaced to swiftmailer library

Resolves #395

2020-12-27 23:11 UTC, antonsviridenko commented
@tugrul 

what is 
`require_once 'vendor/autoload.php';`

where this file is expected to be sourced from?
Bluecherry web UI is packaged into the .deb package and therefore all dependencies should be bundled into the package or be present in Ubuntu LTS repository

2020-12-28 02:32 UTC, tugrul commented
@antonsviridenko It is composer's autoloader script and It is going to present when you run `composer install` in www directory.

This is decent way to manage dependencies of php projects.

You can put install hooks to deb package or you can install dependency before packaging.

2020-12-28 02:43 UTC, curtishall commented
@antonsviridenko php-swiftmailer exists as a deb package if that is easier

2020-12-28 02:45 UTC, tugrul commented
@curtishall `php-swiftmailer` package is too old.  https://github.com/jbouse-debian/php-swiftmailer

composer is best way to use fresh version of php dependencies.

2020-12-29 21:42 UTC, antonsviridenko commented
@tugrul actually I just checked and in all distros that we support there is a latest version 5.4.2 of swiftmailer packaged, and it was released 5 years ago

https://packages.ubuntu.com/search?keywords=php-swiftmailer&searchon=names&suite=bionic&section=all
https://packages.ubuntu.com/search?keywords=php-swiftmailer&searchon=names&suite=focal&section=all
https://packages.debian.org/stable/php/php-swiftmailer

so there is no reason to use compose here when distro package exists in repository

2020-12-29 21:45 UTC, antonsviridenko commented
Or it's not the latest one?

2020-12-29 21:49 UTC, antonsviridenko commented
I guess this one is the new upstream now, right?
https://github.com/swiftmailer/swiftmailer

2020-12-29 21:55 UTC, antonsviridenko commented
Can you provide instructions how to install swiftmailer using composer then? If we decide to bundle dependencies into the .deb file

2020-12-29 22:19 UTC, tugrul commented
@antonsviridenko yes it is official repository and fresh one. Using fresh version is good idea to avoid possible bugs and security holes.

Using composer is very easy I'm going to write common steps below.

You can follow instructions of [this page](https://getcomposer.org/download/) to install composer cli tool if you didn't install before.

You are going to obtain `composer.phar` file in current working directory. It is a runnable php archive file and you can execute it like `./composer.phar`. You can run it in place or you can move it (`mv composer.phar /usr/local/bin/composer`) to bin directory to use globally.

Second step is switching to bluecherry's www directory `cd /path/to/bluecherry/www/` then executing `composer install` cli command. It'is going to read required dependencies `composer.json` and download dependencies inside  `/path/to/bluecherry/www/vendor/` folder.

It is ready to use 👍

2021-01-08 11:02 UTC, antonsviridenko commented
I tried to send test email on a non-configured system (no email settings, no sendmail installed in the system), gives these errors in Apache logs:
```
[Fri Jan 08  05:25:58.659820 2021] [php7:error] [pid 13173] [client 10.0.2.2:54414]  PHP Fatal error:  Uncaught Swift_RfcComplianceException: Address in  mailbox given [] does not comply with RFC 2822, 3.6.2. in  /usr/share/bluecherry/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:355
Stack  trace:
#0  /usr/share/bluecherry/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(272):  Swift_Mime_Headers_MailboxHeader->assertValidAddress('')
#1  /usr/share/bluecherry/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(117):  Swift_Mime_Headers_MailboxHeader->normalizeMailboxes(Array)
#2  /usr/share/bluecherry/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(74):  Swift_Mime_Headers_MailboxHeader->setNameAddresses(Array)
#3  /usr/share/bluecherry/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleHeaderFactory.php(61):  Swift_Mime_Headers_MailboxHeader->setFieldBodyModel(Array)
#4  /usr/share/bluecherry/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleHeaderSet.php(  in  /usr/share/bluecherry/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php  on line 355, referer: https://127.0.0.1:7001/general
--
[Fri  Jan 08 05:26:07.234047 2021] [php7:error] [pid 12702] [client  10.0.2.2:54432] PHP Fatal error:  Uncaught Swift_TransportException:  Expected response code 220 but got an empty response\
og data:
++  Starting Swift_SendmailTransport
!! Expected response code 220 but got  an empty response (code: 0) in  /usr/share/bluecherry/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Plugins/LoggerPlugin.php:124
Stack  trace:
#0  /usr/share/bluecherry/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Events/SimpleEventDispatcher.php(138):   Swift_Plugins_LoggerPlugin->exceptionThrown(Object(Swift_Events_TransportExceptionEvent))
#1   /usr/share/bluecherry/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Events/SimpleEventDispatcher.php(116):  Swift_Events_SimpleEventDispatcher->bubble(Array,  Object(Swift_Events_TransportExceptionEvent), 'exceptionThrown')
#2  /usr/share/bluecherry/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(435):   Swift_Events_SimpleEventDispatcher->dispatchEvent(Object(Swift_Events_TransportExceptionEvent),  'exceptionThrown')
#3 /usr/share/bluecherry/www/v in  /usr/share/bluecherry/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Plugins/LoggerPlugin.php  on line 124, referer: https://127.0.0.1:7001/general

```
and displays 'err ajax' message box in web UI. I think it would be nice to handle these exceptions and display more meaningful error messages to user.

2021-01-08 14:51 UTC, tugrul commented
Because sender email address is empty. It is going to send if you set from address to mail sender configuration on dashboard. I made small change for this. It will not set from address if there is no configuration for this.

2021-01-10 14:24 UTC, antonsviridenko commented
I think we need some more improvements,
I propose to split "SSL: None, TLS/SSL" dropdown list to 3 possible options:
**Security**:

- TLS
- SSL
- None

And make "TLS" default option selected.
Also it is better to have dropdowns for SMTP port number with values 25, 465, 587.

I've just tried to send test email through GMail and it does not accept less secure authentication methods.

2021-01-10 14:30 UTC, antonsviridenko requested changes

2021-01-10 14:30 UTC, antonsviridenko commented on www/ajax/general.php
> +                    $transport->setEncryption('ssl');
Let's have 'tls' here by default. Swift supports  both 'ssl' and 'tls' values here.

2021-01-10 14:30 UTC, antonsviridenko commented on www/template/ajax/general.php
> +                    <label class="control-label col-lg-2"><?php echo G_SMTP_SSL; ?></label>
Let's change label here to something like "Security" or "Transport Security" or "Security Options"

2021-01-10 14:30 UTC, antonsviridenko commented on www/template/ajax/general.php
> +                            <option value='tls' <?php echo ($global_settings->data['G_SMTP_SSL']=='tls') ? 'selected': '';?>>TLS/SSL</option>
Let's split this and make two separate options "TLS" and "SSL"

2021-01-10 15:23 UTC, tugrul commented
I pushed changes. Dropdown for port numbers is not good idea because standard ports not available some cases. Maybe user should use 2525 instead of 25 or something else. Some IT infrastructures not allows to use standard ports and they have to use some workaround like port forwarding or virtual port numbers.

2021-01-10 16:38 UTC, antonsviridenko approved these changes
ok

2021-01-10 16:39 UTC, merged