Update mailer.php
bluecherrydvr/bluecherry-apps pull request #640
Opened 2023-12-31 17:55 UTC by curtishall

Should fix https://github.com/bluecherrydvr/bluecherry-apps/issues/639

2024-01-29 23:38 UTC, andrey-utkin commented on www/lib/mailer.php
> +# If there are no rules (yet) don't display anything bad.
Negation disappeared? I would expect it to be
```
if (!$rules) {
    # If there are no rules (yet) don't display anything bad.
```

2024-01-30 02:20 UTC, curtishall commented on www/lib/mailer.php
> +# If there are no rules (yet) don't display anything bad.
Thanks, fixed

2024-01-30 09:57 UTC, andrey-utkin requested changes

2024-01-30 09:57 UTC, andrey-utkin commented on www/lib/mailer.php
> +if ($!rules) {
This is a syntax error.

```suggestion
if (!$rules) {
```

2024-01-31 13:47 UTC, merged