Update check_dir_permission.sh
bluecherrydvr/bluecherry-apps pull request #642
Opened 2024-01-01 03:03 UTC by curtishall

2024-01-11 23:46 UTC, andrey-utkin requested changes
Could you please clarify the intended effect of the changes felt by the user?

I tested this in runtime and the UI fails to add a location. I am yet to compare this with a build off master branch.

2024-01-11 23:46 UTC, andrey-utkin commented on www/ajax/storagecheck.php
> +        return array('F', 'Unexpected output from shell script: ' . $output);
As I start typing the storage path to add, I keep getting red popups "Unexpected output from shell script: " (with nothing after). This seems to happen even for complete, existing, accessible paths.

Saving additional location fails with the same popups. No reason given. Nothing in the logs (neither /var/log/bluecherry.log, nor /var/log/nginx/bluecherry-error.log.

2024-01-13 01:34 UTC, curtishall commented
@andrey-utkin Code works on https://192.168.86.66:7001/storage (focal, latest from this branch)

Can you test there?  Perhaps we have a permission issue with the script?

2024-01-15 05:34 UTC, curtishall commented on www/ajax/storagecheck.php
> +        return array('F', 'Unexpected output from shell script: ' . $output);
this file was missing from install
/usr/share/bluecherry/scripts/check_dir_permission.sh

2024-01-15 23:46 UTC, andrey-utkin approved these changes
Looks good to me

2024-01-16 00:33 UTC, merged